### ISSUE TITLE
Set energy: integrate set energy functions into Hyperion plans

### ISSUE THREAD

**Issue by olliesilvester** [DiamondLightSource/hyperion#1036]
Once all of the required functions for changing energy have been made in dodal, we should integrate this into Hyperion plan and ensure Hyperion does this instead of GDA

**Acceptance criteria:**

- When Hyperion is being used, GDA no longer does the set energy
- Hyperion does set energy (probably) during the robot load stage
- Sometimes also need to set energy after centring or after one collection
- GDA UI displays the energy that was applied by Hyperion, even if GDA isn't used itself to set the energy directly
- We can still choose to control energy via the old mechanism in GDA via a configuration option.

**Comment by rtuck99** [comment]
Current plan:
* Integrate the undulator and dcm/mirror pitch/roll changes into one set-energy combined plan
* Invoke this plan in the existing hyperion experiment plan during robot load, using energy value supplied from GDA ExtendedCollectionRequest.request.getWavelength()
* remove the callout to set the energy EV in  handle_wavelength, so that GDA doesn't try to set the energy itself
* There are other occasions where we may need to adjust energy between gridscan and rotation scan - we need to determine when these are and how to obtain requested energy for these. TBD
* Leave GDA existing beamlineSpecificEnergy implementation alone. Manual changes in GDA to the energy will result in the legacy GDA energy change code being called.
* When hyperion is not being used for energy changes, revert to original GDA energy change code. Control this via a new property to be checked in GDA gda_or_external_controller
