### ISSUE TITLE
 Make sure zocalo results can't get old results

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/hyperion#1080]
During testing on i03 today it appeared that the zocalo results queue was still populated with the previous results when it was triggered. This can be seen as the crystal found is immediately after the trigger [here](https://graylog2.diamond.ac.uk/search?rangetype=absolute&from=2024-01-16T15%3A10%3A27.000Z&to=2024-01-16T15%3A10%3A29.000Z&q=file%3A%22%5C%2Fdls_sw%5C%2Fi03%5C%2Fsoftware%5C%2Fbluesky%5C%2Fhyperion_v8.5.0%5C%2Fdodal%5C%2Fsrc%5C%2Fdodal%5C%2Fdevices%5C%2Fzocalo%5C%2Fzocalo_results.py%22%20AND%20source%3A%22i03%5C-control.diamond.ac.uk%22%20AND%20gl2_source_input%3A%226317448d3d8af00a49bfed7d%22&highlightMessage=622692aa-b481-11ee-8ab3-1866dafae904&fields=message%2Csource). 

I'm not sure what the root cause of this was exactly.

We also may need to think about what happens if the time zocalo takes becomes 0.

## Acceptance Criteria
* There is no way for the old zocalo results to be accidentally used

**Comment by dperl-dls** [comment]
In _principle_ this should be an issue only if hyperion fails, or if processing is triggered for something which we aren't waiting for. 

The easiest and most comprehensive way to deal with this is probably to just clear the queue whenever we do `run_start()` - at that point we have started on a new sample so any old processing results are probably useless to us. We could log them?

Just for records, [this](https://graylog2.diamond.ac.uk/messages/logs_8609/82d51b60-b47d-11ee-8ab3-1866dafae904) seems to be an example of processing being triggered for a 2D gridscan, and results submitted to the i03 XRC queue, but later crashing hyperion because it doesn't have a [`bounding_box`](https://graylog2.diamond.ac.uk/messages/logs_8609/de3251b0-b47f-11ee-8ab3-1866dafae904)

**Comment by dperl-dls** [comment]
Since we should only have one object subscribed to the results to avoid race conditions, clearing the queue should happen in `ZocaloResults`

**Comment by DominicOram** [comment]
Good spot on the bounding box. We should probably guard that a bit too? Maybe we should have the device unstagable and it remove the subscription during unstage?
