### ISSUE TITLE
Discussion: Reduce nexgen logs

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/hyperion#1168]
Now that we're forwarding `nexgen` info logs to graylog they're getting a bit chatty as `nexgen` logs for each part of the nexus file it's writing and we are writing two files. We should discuss which of these logs are useful to Hyperion/other users of `nexgen` and change either the logs in `nexgen` or the logging level we forward to graylog

## Acceptance Criteria
* We decide which logs we want
* We hide the logs we don't want

**Comment by DominicOram** [comment]
@noemifrisina and @dperl-dls - thoughts?

**Comment by noemifrisina** [comment]
In short, YES. 
In general, the logging in nexgen is in serious need of tidying up - both the set up and the individual message logging levels. One of those tasks that keeps getting pushed back, might be a good time to finally get to it... 
In any case, not sure what level we're sending to Graylog right now but most of the `nexgen` logs should be below it. 
I'd like to keep a file handler where to send most of the messages because they're useful to debug issues eg. for Tristan or ssx (or, more in general, things outside Hyperion), but that can be disabled. I think we definitely don't need to send all these chatty logs to graylog, it should be enough to have a "file is written" or "file writing failed - here's why"

**Comment by DominicOram** [comment]
See [here](https://graylog2.diamond.ac.uk/streams/631745613d8af00a49bfee55/search?rangetype=absolute&fields=message%2Csource&width=1920&highlightMessage=&from=2024-02-20T02%3A24%3A33.000Z&to=2024-02-20T04%3A15%3A16.000Z&q=facility%3Anexgen*) for an example of the nexgen logs we're getting in graylog

**Comment by DominicOram** [comment]
Maybe a good first nexgen issue for @phathaway?

**Comment by noemifrisina** [comment]
> See [here](https://graylog2.diamond.ac.uk/streams/631745613d8af00a49bfee55/search?rangetype=absolute&fields=message%2Csource&width=1920&highlightMessage=&from=2024-02-20T02%3A24%3A33.000Z&to=2024-02-20T04%3A15%3A16.000Z&q=facility%3Anexgen*) for an example of the nexgen logs we're getting in graylog

Yeah, I figure they'd look something like that... Also a good example of how messy the logging levels are, most of those should be set to debug now.

**Comment by noemifrisina** [comment]
> Maybe a good first nexgen issue for @phathaway?

Could be yes. I'll write the issue in nexgen - with a few more details

**Comment by DominicOram** [comment]
Closing as fixed by https://github.com/DiamondLightSource/nexgen/pull/240
