### ISSUE TITLE
Final tidy of the great ispyb refactor

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/hyperion#1218]
Following merge of https://github.com/DiamondLightSource/hyperion/issues/1146 we should do some final tidying:

* `begin_deposition` should just make empty group + N empty data collections then call `update`
* Stop testing the same thing twice as discussed in https://github.com/DiamondLightSource/hyperion/pull/1187#discussion_r1508772344
* `populate_remaining_data_collection_info` should be called straight away after we get the event from the plan with data like transmission etc. Rather than putting that data into `ispyb_params`. We can then remove those field from `ispyb_params`.

**Comment by DominicOram** [comment]
We think 2/3 days

**Comment by rtuck99** [comment]
Not sure about part 1 - as with the current interface, all operations with the database are upserts taking the same arguments, so there's essentially no difference between a row create and a row update - we'd just end up calling exactly the same methods, but twice. Perhaps in a future refactor when we change backends

**Comment by DominicOram** [comment]
>Not sure about part 1 - as with the current interface, all operations with the database are upserts taking the same arguments, so there's essentially no difference between a row create and a row update - we'd just end up calling exactly the same methods, but twice. Perhaps in a future refactor when we change backends

Yh, I think that was my point is there's no difference why not just call `update` for both?

**Comment by rtuck99** [comment]
> > Not sure about part 1 - as with the current interface, all operations with the database are upserts taking the same arguments, so there's essentially no difference between a row create and a row update - we'd just end up calling exactly the same methods, but twice. Perhaps in a future refactor when we change backends
> 
> Yh, I think that was my point is there's no difference why not just call `update` for both?

I've made the change, but I'm not really convinced it makes the code any clearer - there's now more conditionals in the code path. 
It has led to a (minor and arguably more consistent?) behaviour change because previously, specifying a group id didn't update the group on begin_deposition (this was previously retained from before the refactor). It's not as you described, because update already creates the rows, so I don't bother calling anything in the `begin` I just call the entire update which now has additional ID-mangling logic.
