### ISSUE TITLE
Unit tests trying to connect to EPICS devices

### ISSUE THREAD

**Issue by dperl-dls** [DiamondLightSource/hyperion#1257]
See: https://gitlab.diamond.ac.uk/MX-GDA/hyperion-system-testing/-/jobs/175569

**Comment by DominicOram** [comment]
Potentially https://github.com/bluesky/ophyd-async/issues/52? If we're making an ophyd-async device with a list of PVs they wont be connected to the sim unless we use a `DeviceVector`

**Comment by olliesilvester** [comment]
I believe this is ultimately occurring because dodal's `setup_context` doesn't correctly create devices in sim mode. This issue is caused by `test_when_context_created_then_contains_expected_number_of_plans`, and since the beamline is set as I03's, it tries to connect to real devices. (No issue with ophyd-async devices as `connect` is never explicitly called)
