### ISSUE TITLE
Hyperion rotation scan putting beamsize into the subsequent data collection

### ISSUE THREAD

**Issue by olliesilvester** [DiamondLightSource/hyperion#1310]
14:44 https://ispyb.diamond.ac.uk/dc/visit/mx33658-39/id/13466538 synchweb 80x20, actual 80x20
14:47 https://ispyb.diamond.ac.uk/dc/visit/mx33658-39/id/13466550 synchweb 80x20, actual 50x20
14:49 https://ispyb.diamond.ac.uk/dc/visit/mx33658-39/id/13466559 synchweb 50x20, actual 80x20
14:52 https://ispyb.diamond.ac.uk/dc/visit/mx33658-39/id/13466577 synchweb 80x20, actual 50x20

### Acceptance Criteria

- Identify issue, fix and add tests to prove fix

**Comment by DominicOram** [comment]
I spent a couple of hours on the beamline trying to diagnose this. The issue seems to be that when the Hyperion XRC works out which aperture to use based on xtal size and passes this back to GDA then GDA doesn't correctly update itself and pass the information to Hyperion for the rotation. Rather than try and fix GDA into doing this a better solution would be to instead read the aperture correctly in the rotation plan and no longer rely on GDA for this at all (https://github.com/DiamondLightSource/hyperion/issues/1311) Therefore closing this in favour of that
