### ISSUE TITLE
Rotation scans get an extra `_1` on the end of the filename

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/hyperion#1345]
It looks like Hyperion is adding the run_number on to the rotation scan twice i.e. see data in `/dls/i03/data/2024/cm37235-2/TestInsulin/ins_9` where we get `ins_9_8_1.nxs`. Here the 8 is the runnumber appended by GDA and passed into Hyperion and the `_1` is Hyperion adding another run number on. This is probably best fixed by just not including the run number when GDA gives the filename to Hyperion

## Acceptance Criteria
* Rotation scans do not have the additional `_1`

**Comment by olliesilvester** [comment]
I believe this was being caused by the GDA line which gets the prefix for hyperion's rotation parameters:
`prefix = extended_request.getDnaFilePrefix()[:-1]`
In Hyperion's debug logs, the prefix from this line included the underscore + runnumber from the previous hyperion FGS. Then, the Hyperion line     
```
@property
 def full_filename(self):
     return f"{self.prefix}_{self.run_number}"
```
Would add on another underscore run-number.

**Comment by olliesilvester** [comment]
See solution at https://gerrit.diamond.ac.uk/c/gda/gda-mx/+/41720/1. To test, cherry pick this change onto i03-live and test on a beamline (doesn't require beam)

**Comment by olliesilvester** [comment]
Deployed GDA change on `i03_live` and it appeared to fix issue
