### ISSUE TITLE
Get PandA PCAP working

### ISSUE THREAD

**Issue by olliesilvester** [DiamondLightSource/hyperion#1485]
The PandA is now configured to save position encoder values to an h5 value in the specified panda directory. Hyperion is already configured to do this, we just haven't tested it yet. We may need to set the filename at some point in our plan. This would be via the signal `panda.data.hdf_file_name`

**Comment by DominicOram** [comment]
* We would like the positions to be saved next to the diffraction data e.g. `/dls/i03/data/2024/cm37235-3/TestProteinaseK/protk_1`
* We then probably want a comparison script that confirms https://github.com/DiamondLightSource/hyperion/issues/1474 is working, this can just be an offline script rather than part of hyperion

**Comment by rtuck99** [comment]
Looks like the `PandaHDFWriter` already sets the requisite PV using the path obtained from the `DirectoryProvider`, therefore should just be a matter of analysing the generated data
